# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClusterCodex < Formula
  desc "Generate Kubernetes Bill of Materials for a Kubernetes cluster."
  homepage "https://github.com/guidewire-oss"
  version "0.0.1"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.1/clx_0.0.1_darwin_amd64.tar.gz"
      sha256 "9884cf7acbcb339dc8c3b1363671c0fb9ae2f329eba32e02340dfc97bd239473"

      def install
        bin.install "clx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.1/clx_0.0.1_darwin_arm64.tar.gz"
      sha256 "e7a613512b1ea9bc7e7f5fbdba0a324f98474d26facac462b2af926df5de50d1"

      def install
        bin.install "clx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.1/clx_0.0.1_linux_amd64.tar.gz"
        sha256 "c052048ad13f1ba0d4b5054c6aba05b033b1b4184d0b1ddf3b0d665cfdcd36e4"

        def install
          bin.install "clx"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.1/clx_0.0.1_linux_arm.tar.gz"
        sha256 "22ed4603882310d11ff1aec8d21673a312b1c5c2f64bc8076f4c143a1e39c932"

        def install
          bin.install "clx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.1/clx_0.0.1_linux_arm64.tar.gz"
        sha256 "ac8570bda25dbc327fdabf70064416e2940bcedab4fd48e45ee21f9d74c41d51"

        def install
          bin.install "clx"
        end
      end
    end
  end

  test do
    system "#{bin}/clx", "version"
  end
end
