# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clx < Formula
  desc "Generate Kubernetes Bill of Materials for a Kubernetes cluster."
  homepage "https://github.com/guidewire-oss"
  version "0.0.2"
  license "Apache 2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.2/clx_0.0.2_darwin_amd64.tar.gz"
      sha256 "52f87d0028c5b3b9efbd90da19938d6784fb96bf2e8f74f794729427dac51e87"

      def install
        bin.install "clx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.2/clx_0.0.2_darwin_arm64.tar.gz"
      sha256 "3dff77e7e2cec576f95ead5928a12766e03abc3a18a4f2e6eb1df686e5265bc4"

      def install
        bin.install "clx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.2/clx_0.0.2_linux_amd64.tar.gz"
        sha256 "cf7a7b120069b6457100d1d3e73433fa978d921179082d33ea02680c922a80b1"

        def install
          bin.install "clx"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.2/clx_0.0.2_linux_arm.tar.gz"
        sha256 "87b962a1588821f6022ce4fdc949a7033539a96ee1186a94fdaa682476ec9eaa"

        def install
          bin.install "clx"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/guidewire-oss/cluster-codex/releases/download/v0.0.2/clx_0.0.2_linux_arm64.tar.gz"
        sha256 "4a146afc9a6624295e6ee7541afcd95afe5a4d63ae50c29fcc724fff73c32a4d"

        def install
          bin.install "clx"
        end
      end
    end
  end

  test do
    system "#{bin}/clx", "version"
  end
end
